[profile.default]
# Directory Setup
script = "script"
src = "contracts"
test = "test"

# Compiler Options
evm_version = "paris"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.28"

# Permissions
fs_permissions = [{access = "read-write", path = "./"}]

additional_compiler_profiles = [
  {name = "test", via_ir = false},
]

compilation_restrictions = [
  {paths = "test/**", via_ir = false},
]
